version: '3.8'

services:
  app:
    image: gbacentrotecnico/acordos:latest
    environment:
      - PORT=3000
      - NODE_ENV=production
      - ADMIN_EMAIL=admin@gbamecanica.com.br
      - ADMIN_PASS=gbamecanica010203
      - JWT_SECRET=8fV2pL9mKq4xR7wN3zY6cXbV1aM5nH8jD0cT4vB9mF2lK7pQ3wE6rY1tU8iO
      - DATABASE_URL=postgres://postgres:gbamecanica010203@postgres:5432/acordos
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=gbamecanica010203
      - DB_NAME=acordos
      - EVOLUTION_API_URL=
      - EVOLUTION_API_TOKEN=
      - EVOLUTION_INSTANCE=

    networks:
      - network_swarm_public
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.acordos.rule=Host(`acordos.gbamecanica.com.br`)"
        - "traefik.http.routers.acordos.entrypoints=websecure"
        - "traefik.http.routers.acordos.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.acordos.loadbalancer.server.port=3000"

  postgres:    
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gbamecanica010203
      - POSTGRES_DB=acordos
      - TZ=America/Sao_Paulo      
    networks:
      - network_swarm_public    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  network_swarm_public:
    external: true

volumes:
  postgres_data:
